blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/',
                                views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
                                views.post_detail,
                                name='post_detail'),
    path('<int:post_id>/share/',
                                views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    # views
    path('index/', views.index, name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager



class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                self).get_queryset()\
                    .filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
            ('draft', 'Draft'),
            ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                            on_delete=models.CASCADE,
                            related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                            choices=STATUS_CHOICES,
                            default='draft')
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()
    
    class Meta:
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
            args=[self.publish.year,
                self.publish.month,
                self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                            on_delete=models.CASCADE,
                            related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                                widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # ... send email
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                        f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                        f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com',
                        [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                'blog/post/list.html',
                {'page': page,
                 'posts': posts,
                 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                    status='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    
    new_comment = None
    
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                            .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                            .order_by('-same_tags','-publish')[:4]

    return render(request,
                'blog/post/detail.html',
                {'post': post,
                'comments': comments,
                'new_comment': new_comment,
                'comment_form': comment_form,
                'similar_posts': similar_posts})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight = 'A') + \
                            SearchVector('body', weight = 'B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                    similarity=TrigramSimilarity('title', query),
                    ).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request,
                'blog/post/search.html',
                {'form': form,
                'query': query,
                'results': results})












def index(request):
    return render(request,
                'blog/post/index.html')

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog. I've written {% total_posts %} posts so far.</p>
        
        <h3>Latest posts</h3>
        {% show_latest_posts 3 %}

        <h3>Most commented posts</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
        <p>
            <a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a>
        </p>
    </div>
</body>
</html>

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>
 

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
        Share this post
        </a>
    </p>
    
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        
        There are no similar posts yet.
    
    {% endfor %}
    
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
    <header id="main-container">
        <div class="container">
            <h1>My Website</h1>
        </div>
    </header>
    <nav id="navbar">
        <div class="container">
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </div>
    </nav>

    <section id="showcase">
        <div class="container">
            <p>Lorem ipsum dolor sit, 
                amet consectetur adipisicing elit. 
                Iste, dolores!
            </p>
        </div>
    </section>
    <div class="container">
        <section id="main">
            <h1>Welcome</h1>
            <p>Lorem ipsum dolor sit, 
                amet consectetur adipisicing elit. 
                Iste, dolores!
            </p>
        </section>
        <aside id="sidebar">
            <p>Lorem ipsum dolor sit, 
                amet consectetur adipisicing elit. 
                Iste, dolores!
            </p>
        </aside>
    </div>

    <footer id="main-footer">
        <p>Copyright &copy; 2017 My Website</p>
    </footer>
    <!-- <div class="container">
        <div class="box-1">
            <h1>Hi World</h1>
            <p>
                Lorem ipsum dolor, sit amet consectetur 
                adipisicing elit. Illum modi quis, iste 
                explicabo, tempore praesentium dignissimos 
                cupiditate expedita minima eveniet maiores
                mollitia voluptatem deserunt
                esse architecto beatae accusantium incidunt atque.
            </p>
        </div>
        <div class="box-2">
            <h1>Hello World</h1>
            <p>
                Lorem ipsum dolor, sit amet consectetur 
                adipisicing elit. Illum modi quis, iste 
                explicabo, tempore praesentium dignissimos 
                cupiditate expedita minima eveniet maiores
                mollitia voluptatem deserunt
                esse architecto beatae accusantium incidunt atque.
            </p>
            <a href="#" class="button">Read More</a>
        </div>
        <div class="categories">
            <h2>Categories</h2>
            <ul>
                <li><a href="#">Category 1</a></li>
                <li><a href="#">Category 2</a></li>
                <li><a href="#">Category 3</a></li>
                <li><a href="g#">Category 4</a></li>
            </ul>
        </div>
        <form action="" class="my-form">
            <div class="form-group">
                <label for="">Name: </label>
                <input type="text" name="name">
            </div>
            <div class="form-group">
                <label for="">Email: </label>
                <input type="text" name="email">
            </div>
            <div class="form-group">
                <label for="">Message: </label>
                <textarea name="message" id="" cols="30" rows="10"></textarea>
            </div>
            <input class="button" type="submit" value="Submit" name="">
        </form>
        <div class="block">
            <h3>Heading</h3>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing
                 elit. 
            </p>
        </div>
        <div class="block">
            <h3>Heading</h3>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing
                 elit. 
            </p>
        </div>
        <div class="block">
            <h3>Heading</h3>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing
                 elit. 
            </p>
        </div>
        <div class="clr"></div>
        
        <div id="main-block">
            <h3>Heading</h3>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing
                 elit. 
            </p>
        </div>

        <div id="sidebar">
            <h3>Heading</h3>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing
                 elit. 
            </p>
        </div>
        <div class="clr"></div>

        <div class="p-box">
            <h1>Hello</h1>
            <h2>Hi</h2>
        </div>

        <ul class="my-list">
            <li>List Item</li>
            <li>List Item</li>
            <li>List Item</li>
            <li>List Item</li>
            <li>List Item</li>
            <li>List Item</li>
            <li>List Item</li>
            <li>List Item</li>
            <li>List Item</li>
            <li>List Item</li>
        </ul>
    </div>

    <a class="fix-me button" href="">Hello</a>
    <div style="margin-top:500px;"></div> --> 
</body>
</html>

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>

    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
            
                {{ post.title }}
            
            </a>
        </h2>
        
        <p class="date">
         
            Published {{ post.publish }} by {{ post.author }}
        </p>
        
        {{ post.body|markdown|truncatewords_html:30 }}
        
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <!-- <p class="tags">Tags: {{ post.tags.all|join:", " }}</p> -->
    
    {% endfor %}

    {% include "blog/pagination.html" with page=posts %}

{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|markdown|truncatewords_html:5 }}
            {% empty %}
                <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
        {% else %}
        <h1>Search for posts</h1>
        <form method="get">
        {{ form.as_p }}
        <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}